language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-express-webapp' ]; then cd .. && eval "mv $currentfolder generator-express-webapp" && cd generator-express-webapp; fi

